name: CI tests

on: [push, pull_request, workflow_dispatch]

jobs:
  ci_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test library
        run: yarn test:lib --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: Test schematics
        run: yarn test:schematics
