name: Run linter and tests against lib and schematics

on: [push, pull_request]

jobs:
  lint+test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint
      - name: Test
        run: |
        npm run test:lib -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        npm run test:schematics
